<?php

/* ============================================================
 * 项目：元点Admin SaaS
 * ============================================================ */

declare(strict_types=1);

namespace core\mobile;

use app\repository\plugin\PluginRepository;
use app\service\saas\EntitlementService;

/**
 * DIY 渲染器协议 v1：按租户权益重写生产构建产物的两个生成物——
 * {uniappDir}/src/generated/diy-plugin-renderers.ts（type 集合）与
 * {uniappDir}/src/components/diy/plugin-renderer-host.generated.vue（静态分支宿主，
 * 小程序编译器不支持 <component :is>，动态分发只能编译期展开为 v-if 链）。
 *
 * dev 态由 scripts/sync-plugin-uniapp.mjs 全量生成（不做权益过滤）；生产构建的
 * 模板复制会把 dev 版带进产物，其中可能 import 未授权插件的组件（源码未被
 * PluginUniappCopier::copyDiyRenderers 复制），uni build 会因文件不存在而失败——
 * 因此本类必须在复制授权源码之后、构建之前按权益重写两个生成物。
 *
 * 只收录「声明合法（裸组件名）+ 组件文件确实已复制到产物」的条目；文件缺失
 * 时静默跳过（宿主 type 未命中 → 核心通用回退，与三端统一回退契约一致）。
 */
final class DiyRendererRegistryGenerator
{
    private const NAME_RE = '/^[A-Za-z][A-Za-z0-9_-]*$/';

    public function __construct(
        private readonly PluginRepository $pluginRepository,
        private readonly EntitlementService $entitlementService,
    ) {
    }

    /**
     * @return array<int, string> 写入注册表的 widget type 列表
     */
    public function write(string $uniappDir, int $tenantId): array
    {
        /** @var array<int, array{type:string,code:string,name:string}> $entries */
        $entries = [];

        foreach ($this->entitlementService->list($tenantId) as $ent) {
            $plugin = $this->pluginRepository->findByEntitlement($ent->code);
            if (!$plugin) {
                continue;
            }
            $code = (string) ($plugin['code'] ?? '');
            $manifest = is_array($plugin['manifest'] ?? null)
                ? $plugin['manifest']
                : (json_decode((string) ($plugin['manifest'] ?? ''), true) ?: []);

            foreach ((array) ($manifest['diy_widgets'] ?? []) as $w) {
                if (!is_array($w)) {
                    continue;
                }
                $type = (string) ($w['type'] ?? '');
                $name = $w['renderer']['uniapp'] ?? null;
                if ($type === '' || !is_string($name) || !preg_match(self::NAME_RE, $name)) {
                    continue;
                }
                if (!is_file("{$uniappDir}/src/components/diy/plugins/{$code}/{$name}.vue")) {
                    continue; // 未复制/缺失 → 跳过，端上走核心通用回退
                }
                $entries[] = ['type' => $type, 'code' => $code, 'name' => $name];
            }
        }

        $types = array_column($entries, 'type');

        $tsContent = implode("\n", [
            '// AUTO-GENERATED by core\mobile\DiyRendererRegistryGenerator（按租户权益过滤）— do not edit.',
            'export const DIY_PLUGIN_RENDERER_TYPES = new Set<string>(' . json_encode($types, JSON_UNESCAPED_SLASHES) . ')',
            '',
        ]);

        $branches = [];
        $imports = [];
        foreach ($entries as $i => $e) {
            $cond = $i === 0 ? 'v-if' : 'v-else-if';
            $branches[] = "  <R{$i} {$cond}=\"type === '{$e['type']}'\" :props=\"props\" />";
            $imports[] = "import R{$i} from '@/components/diy/plugins/{$e['code']}/{$e['name']}.vue'";
        }
        $vueContent = implode("\n", [
            '<!-- AUTO-GENERATED by core\mobile\DiyRendererRegistryGenerator（按租户权益过滤）— do not edit. -->',
            '<template>',
            ...($entries === [] ? ['  <!-- 无插件 DIY 渲染器 -->'] : $branches),
            '</template>',
            '',
            '<script setup lang="ts">',
            ...$imports,
            'defineProps<{ type: string; props: Record<string, any> }>()',
            '</script>',
            '',
        ]);

        $dir = $uniappDir . '/src/generated';
        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new \RuntimeException("failed to mkdir {$dir}");
        }
        file_put_contents($dir . '/diy-plugin-renderers.ts', $tsContent);
        file_put_contents($uniappDir . '/src/components/diy/plugin-renderer-host.generated.vue', $vueContent);

        return $types;
    }
}
